DEV: Unify mixed dimensional grid generation (functionality) (#838)
* WIP: Mixed-dimensional grid generation

* WIP: Collecting examples of mdg generation

* DEV: Including a draft for creation of md-grids

* WIP: First try to unifying simplexes meshes

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* ENH: Resolving circular importing

* FIX: add missing scope

* WIP: Mixed-dimensional grid generation

* WIP: Collecting examples of mdg generation

* DEV: Including a draft for creation of md-grids

* WIP: First try to unifying simplexes meshes

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Resolving circular importing

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* ENH: Resolving circular importing

* MAINT: Was confused and forgot two files during: Merge branch '780-unify-fracture-network-generation-in-2d-and-3d' of https://github.com/pmgbergen/porepy into 780-unify-fracture-network-generation-in-2d-and-3d

* TST: Network definition for 2d model tests

* Revert "Merge branch 'develop' into 780-unify-fracture-network-generation-in-2d-and-3d"

This reverts commit 43c3c30b29ee0dcf0ee900bd1c1a2a9439fff6f4, reversing
changes made to 38e82960d34dd543f76dce2cf5357e35e5a78f85.

* STY: isort, black and flake8

* WIP: Collecting examples of mdg generation

* DEV: Including a draft for creation of md-grids

* WIP: First try to unifying simplexes meshes

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Resolving circular importing

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* ENH: Resolving circular importing

* STY: isort, black and flake8

* Revert "Revert "Merge branch 'develop' into 780-unify-fracture-network-generation-in-2d-and-3d""

This reverts commit 8184dcefbb6fc19061e9447f63dce6e4394c74e1.

* BUGFIX: Use `fractures` to construct the fracture network

* TST: Fix failing tests

Fix test_mandel_biot.py
Fix test_fracture_mesh_generation.py
Fix test_contact_mechanics.py
Fix test_tag_gmsh.py
Fix test_darcy_mortar.py
Fix test_vtk.py

* BUGFIX: Two fixes (see description)

- Transform to pts/edges only if `fractures` is NOT an empty list. This fixes some bugs generated by trying to stack non-existing points.
- Treat empty list of fractures as `None` in `copy()` method.

* TST: Fix test_grid_factory.py

* BUGFIX: Wrong order of arguments in super().__init__()

* DOC: Minor improvements in documentation

* BUG: Indentation error in Ad maximum function.

Also updated pp.ad.functions.py to comply with mypy v1.0.0

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Wrapper method for fracture network generation

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* TST: Update fracture network definition

* ENH: Resolving circular importing

* TST: Network definition for 2d model tests

* FIX: add missing scope

* BUGFIX: Use `fractures` to construct the fracture network

* TST: Fix failing tests

Fix test_mandel_biot.py
Fix test_fracture_mesh_generation.py
Fix test_contact_mechanics.py
Fix test_tag_gmsh.py
Fix test_darcy_mortar.py
Fix test_vtk.py

* BUGFIX: Two fixes (see description)

- Transform to pts/edges only if `fractures` is NOT an empty list. This fixes some bugs generated by trying to stack non-existing points.
- Treat empty list of fractures as `None` in `copy()` method.

* TST: Fix test_grid_factory.py

* BUGFIX: Wrong order of arguments in super().__init__()

* DOC: Minor improvements in documentation

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* ENH: Resolving circular importing

* FIX: add missing scope

* WIP: Mixed-dimensional grid generation

* WIP: Collecting examples of mdg generation

* DEV: Including a draft for creation of md-grids

* WIP: First try to unifying simplexes meshes

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Resolving circular importing

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* ENH: Resolving circular importing

* MAINT: Was confused and forgot two files during: Merge branch '780-unify-fracture-network-generation-in-2d-and-3d' of https://github.com/pmgbergen/porepy into 780-unify-fracture-network-generation-in-2d-and-3d

* TST: Network definition for 2d model tests

* Revert "Merge branch 'develop' into 780-unify-fracture-network-generation-in-2d-and-3d"

This reverts commit 43c3c30b29ee0dcf0ee900bd1c1a2a9439fff6f4, reversing
changes made to 38e82960d34dd543f76dce2cf5357e35e5a78f85.

* STY: isort, black and flake8

* WIP: Collecting examples of mdg generation

* DEV: Including a draft for creation of md-grids

* WIP: First try to unifying simplexes meshes

* MAINT: Change FractureNetwork2d initialization to take LineFractures instead of points and edges.

* ENH: Resolving circular importing

* ENH: Add tags to the `Fracture` class and change the generation of a `FractureNetwork2d` accordingly

* ENH: Resolving circular importing

* STY: isort, black and flake8

* Revert "Revert "Merge branch 'develop' into 780-unify-fracture-network-generation-in-2d-and-3d""

This reverts commit 8184dcefbb6fc19061e9447f63dce6e4394c74e1.

* BUGFIX: Use `fractures` to construct the fracture network

* TST: Fix failing tests

Fix test_mandel_biot.py
Fix test_fracture_mesh_generation.py
Fix test_contact_mechanics.py
Fix test_tag_gmsh.py
Fix test_darcy_mortar.py
Fix test_vtk.py

* BUGFIX: Two fixes (see description)

- Transform to pts/edges only if `fractures` is NOT an empty list. This fixes some bugs generated by trying to stack non-existing points.
- Treat empty list of fractures as `None` in `copy()` method.

* TST: Fix test_grid_factory.py

* BUGFIX: Wrong order of arguments in super().__init__()

* DOC: Minor improvements in documentation

* BUG: Indentation error in Ad maximum function.

Also updated pp.ad.functions.py to comply with mypy v1.0.0

* ENH: Adds md-grid generation module

* WIP: Partial unification of simplexes

* WIP: Initial step on testing high-level mdg generation

* WIP: Survey and Collect args for high-level mdg generation

* WIP: Processing simplex signature via inspect

* WIP: Encapsulates signature preprocessing

* WIP: Make fracture network mandatory

* FIX: Solve some Flake8 issues

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* FIX: mypy on mdg_generation

* MAINT: black and flake8 on mdg_generation

* FIX: Type error in test_mdg_generation on python 3.8

* MAINT: Adding support for DFN models

* MAINT: black on mdg_generation

* MAINT: Fix mypy incompatible types in assignment

* MAINT: flake, isort and black on test_mdg_generation

* DOC: Partial documentation of pp.create_mdg

* WIP: ongoing work with extra arguments on meshing_args

* STY:  black, isort and mypy on mdg_generation.py

* MAINT: Correct a TypeError message.

* MAINT: Improving test coverage and apply review changes.

* MAINT: Documentation and minor changes ot mdg_generation

* STY: Minor changes to mdg_generation documentation

* MAINT: Improves test documentation

* FIX: Reintroduce deleted code from a previous commit

* MAINT: Second sprint on improving documentation

test_mdg_generation.py
mdg_generation.py

* DOC: Third sprint on improving documentation

Third sprint on improving documentation

* MAINT: black and flake8

* Update tests/integration/test_mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update tests/integration/test_mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update tests/integration/test_mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update tests/integration/test_mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update tests/integration/test_mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* Update tests/integration/test_mdg_generation.py

Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>

* MAINT: Applying review changes.

* MAINT: Applying review changes and adding more typing

* MAINT: Fix TypeError for python 3.8

* MAINT: Add a ValueError message because issue #846

* MAINT: black on mdg_generation.py

* MAINT: Fix a bug after applying review changes.

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* Update src/porepy/grids/mdg_generation.py

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>

* MAINT: Applying changes from code review.

---------

Co-authored-by: Jhabriel Varela <jhabriel@gmail.com>
Co-authored-by: pschultzendorff <peter@schultzendorff.de>
Co-authored-by: Ivar Stefansson <ivar.stefansson@uib.no>
Co-authored-by: Jhabriel Varela <11464732+jhabriel@users.noreply.github.com>
Co-authored-by: Eirik Keilegavlen <Eirik.Keilegavlen@uib.no>
Co-authored-by: solveigste <solveig.stefansdottir@gmail.com>